apiVersion: v1
kind: Service
metadata:
  name: svc1
spec:
  type: ClusterIP # Tạo ra service mà cho các thành phần khác trên cùng một cluster có thể truy cập đến
  ports:
  - port: 80
    targetPort: 80
